name: Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to latest version

      - name: Generate Snake SVG
        uses: Platane/snk@v3  # Check for the latest version
        with:
          github_user_name: awais1019  # Updated input parameter
          outputs: dist/github-contribution-grid-snake.svg  # Updated input parameter
