name: Snake

on:
  schedule:
    - cron: '0 0 * * *' # Update daily
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user: awais1019
          output: dist/github-contribution-grid-snake.svg
